In [1]:
import torch

In [2]:
a = torch.empty(2,3)

In [3]:
type(a)

torch.Tensor

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2,3)

tensor([[0.3501, 0.3316, 0.6922],
        [0.1074, 0.3408, 0.3447]])

In [7]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [8]:
torch.tensor([[1,2,3],
              [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
torch.arange(0,20,5)

tensor([ 0,  5, 10, 15])

In [10]:
torch.linspace(0,10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [11]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [13]:
a = torch.rand(2,3)
a.shape

torch.Size([2, 3])

In [14]:
torch.zeros(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
a.dtype

torch.float32

In [16]:
b = torch.tensor([1,2,3], dtype = torch.float32)

In [17]:
b

tensor([1., 2., 3.])

In [18]:
b.to(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
b+3

tensor([4., 5., 6.])

In [20]:
c = torch.rand(3,4)
c

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [21]:
torch.round(c)

tensor([[1., 1., 1., 0.],
        [1., 1., 0., 1.],
        [0., 0., 0., 1.]])

In [22]:
torch.ceil(c)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
torch.floor(c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
c = c*100
c

tensor([[86.9404, 56.7715, 74.1094, 42.9404],
        [88.5443, 57.3904, 26.6580, 62.7449],
        [26.9632, 44.1364, 29.6921, 83.1685]])

In [25]:
torch.clamp(c, min = 5, max = 80)

tensor([[80.0000, 56.7715, 74.1094, 42.9404],
        [80.0000, 57.3904, 26.6580, 62.7449],
        [26.9632, 44.1364, 29.6921, 80.0000]])

In [26]:
torch.sum(c)

tensor(680.0597)

In [27]:
torch.sum(c , dim = 0)

tensor([202.4479, 158.2983, 130.4595, 188.8539])

In [28]:
torch.mean(c, axis = 1)

tensor([65.1905, 58.8344, 45.9900])

In [30]:
torch.median(c)

tensor(56.7715)

In [31]:
torch.var(c)
torch.std(c)

tensor(23.0269)

In [32]:
torch.argmax(c)

tensor(4)

In [33]:
a = torch.arange(1,10)
a = a.to(torch.float32)
a = a.reshape(3,3)
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [34]:
torch.det(a)

tensor(0.)

In [35]:
torch.sigmoid(a)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975],
        [0.9991, 0.9997, 0.9999]])

In [36]:
torch.softmax(a, dim = 0)

tensor([[0.0024, 0.0024, 0.0024],
        [0.0473, 0.0473, 0.0473],
        [0.9503, 0.9503, 0.9503]])

In [37]:
print(a)
a.add_(5)  # inplace
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [38]:
a

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])

In [39]:
b = a
b

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])

In [40]:
a[0][0] = 0
print(a)
print(b)

tensor([[ 0.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor([[ 0.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [41]:
b = a.clone()
print(b)
a[0][0] = 10
print(a)
print(b)

tensor([[ 0.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor([[10.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor([[ 0.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [42]:
device = torch.device('cuda')
device

device(type='cuda')

In [43]:
torch.rand(2,3).to(device)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]], device='cuda:0')

In [49]:
a = torch.rand((2,3), device = device)

In [50]:
a + 5

tensor([[5.8259, 5.2128, 5.7292],
        [5.3209, 5.7550, 5.2132]], device='cuda:0')

In [51]:
a.to('cpu')


tensor([[0.8259, 0.2128, 0.7292],
        [0.3209, 0.7550, 0.2132]])

In [52]:
a.flatten()

tensor([0.8259, 0.2128, 0.7292, 0.3209, 0.7550, 0.2132], device='cuda:0')

In [54]:
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [55]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [56]:
import numpy as np

In [57]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [60]:
b = a.numpy()
type(b)

numpy.ndarray

In [61]:
torch.from_numpy(b)

tensor([1, 2, 3])