In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
x, y = make_classification(n_samples=10,
                           n_features=2,
                           n_informative=2,
                           n_redundant=0,
                           n_classes=2,
                           random_state=42)

In [4]:
x.shape

(10, 2)

In [5]:
y.shape

(10,)

In [6]:
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [7]:
from torch.utils.data import Dataset, DataLoader

In [8]:
class CustomDataset(Dataset):
  def __init__(self, features, labels) :
    self.features = features
    self.labels = labels

  def __len__(self) :
    return self.features.shape[0]

  def __getitem__(self, idx) :
    return self.features[idx], self.labels[idx]

In [9]:
dataset = CustomDataset(x,y)

In [10]:
len(dataset)

10

In [11]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [12]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [13]:
for batch_features, batch_labels in dataloader :
  print(batch_features)
  print(batch_labels)
  print('-'*50)

tensor([[-1.9629, -0.9923],
        [ 1.8997,  0.8344]])
tensor([0., 1.])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.5872, -1.9717]])
tensor([1., 0.])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-1.1402, -0.8388]])
tensor([1., 0.])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]])
tensor([0., 1.])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.0683, -0.9701]])
tensor([0., 1.])
--------------------------------------------------
